### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by VaniaZet** [konsim83/TriangleMesh.jl#11]
Hi! When loading a package, it displays an error:

ERROR: Unsatisfiable requirements detected for package TriangleMesh [e5719326]:
 TriangleMesh [e5719326] log:
 ├─possible versions are: 0.1.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by konsim83** [comment]
Hi VaniaZet, 
Yes, I know. The latest version of the package is not registered yet. You can avoid this by cloning directly from github. In the package manager type

pkg> add  https://github.com/konsim83/TriangleMesh.jl
 
This should fix it for now. I am working to register the new versions now automatically

Cheers,
Konrad
