### ISSUE TITLE
It shows one module in the library is missing

### ISSUE THREAD

**Issue by WeiZhang111** [konsim83/TriangleMesh.jl#25]
I am using Windows system and I have visual studio community 2017 on my laptop. The error is like this - how may I fix this? Thx

![image](https://user-images.githubusercontent.com/83143548/115974706-65e1cf00-a556-11eb-8a44-fdb442b3bac9.png)

**Comment by konsim83** [comment]
It seems like the library was not built. Did you try to do that manually? I do not have so much time to invest in this package but an improvement of the built would be great. See this #19 A patch would be very welcome :-)

**Comment by WeiZhang111** [comment]
> It seems like the library was not built. Did you try to do that manually? I do not have so much time to invest in this package but an improvement of the built would be great. See this #19 A patch would be very welcome :-)

Thanks! It has been resolved - I tried build and update. Thx
